server {
  # listen 80;
  listen ${PORT};
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback — สำคัญสำหรับ react-router
  location / {
    try_files $uri $uri/ /index.html;
  }

  # cache static assets
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}